CREATE TABLE FORM (
    USERNAME VARCHAR2(30) ,
    PASSWORD VARCHAR(30),
    EMAIL VARCHAR2(30) PRIMARY KEY,
    DOB DATE
);

Create table cinema (
    CINEMA_ID INT Primary KEY,
    CINEMA_NAME VARCHAR2(30),
    CITY VARCHAR2(30)
);
create table movies(
   MOVIE_ID int primary key,
   TITLE varchar2(256),
   DESCRIPTION varchar2(512),
   LENGTH int,
   LANG varchar2(20),
   RELEASE_DATE date,
   GENRE varchar2(20)
);
CREATE TABLE shows (
    Show_Id INT PRIMARY KEY,
    Cinema_Id INT,
    FOREIGN KEY (CINEMA_ID) REFERENCES CINEMA(CINEMA_ID),
    MOVIE_ID INT,
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID),
    screen_no int,
    SHOW_TIMEING DATE
);
CREATE TABLE BOOKING (
    SHOW_ID INT,
    FOREIGN KEY (SHOW_ID) REFERENCES SHOWS(SHOW_ID),
    AVAILABLE_SEAT INT
);
CREATE TABLE TICKETS(
    TICKET_ID INT PRIMARY KEY,
    USER_ID INT,
    SHOW_ID INT,
    NO_OF_TICKET INT,
    TOTAL_COST FLOAT
);
CREATE TABLE SEATS(
    TICKET_ID INT,
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(TICKET_ID),
    ROW_NO CHAR(2),
    SEAT_NO INT
);
CREATE TABLE BILL(
    USER_ID VARCHAR2(30),
    TICKET_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES FORM(EMAIL),
    FOREIGN KEY (TICKET_ID) REFERENCES TICKETS(TICKET_ID),
    PAYMENT_METHOD VARCHAR2(20),
    STATUS CHAR(5)
);
